### ISSUE TITLE
Proposal: NativeIO

### ISSUE THREAD

**Issue by fivedots** [WICG/proposals#10]
## Introduction

We would like to collaborate on NativeIO, a performant and generic storage API.

Please see [the Explainer](https://github.com/fivedots/nativeio-explainer) for more information.

## Feedback

I welcome feedback in this thread, but encourage you to file bugs against [the Explainer](https://github.com/fivedots/nativeio-explainer)

**Comment by alshamma** [comment]
Adobe applications work on documents that often contain large amounts of data. This data can be text, raster, video and so on. The data in a document is typically larger than available RAM. File sizes in excess of 1GB are not uncommon. When operating in a desktop environment, applications can read and write to local storage, both for scratch space while editing, and as a cache when operating on cloud documents. When dealing with large files, performance of reading and writing data between RAM and local storage is critical.

When running in a browser, Adobe web apps, or, apps, must also allow editing of documents larger than the available RAM. Apps must be able to cache large documents on a local machine to avoid the time and network traffic to re-download data. And, apps must be able to store working data to disk. A key example of working data is the undo history for raster or video based operations. During a long edit session, the working data can be many multiples of the original file size.

Adobe needs a highly performant way to read and write large amounts of working data to the local file system that is secure, origin-private, and a seamless experience for our users. Storage Foundation provides the best available means to achieve this.

**Comment by yoavweiss** [comment]
The repo now lives under https://github.com/WICG/storage-foundation-api-explainer

Happy incubation!!
