### ISSUE TITLE
Extending the PointerEvent with Unique DeviceId Attribute

### ISSUE THREAD

**Issue by sahirv** [WICG/proposals#101]
## Introduction

As devices with advanced pen input capabilities are becoming increasingly prevalent, it is important that the web platform continues to evolve to fully support these advanced features in order to unlock rich experiences for both end users and developers. One such advancement is the ability for a device's digitizer to recognize more than one pen device interacting with it simultaneously. In this Explainer, we propose an extension to the PointerEvent interface to include a new attribute, deviceId, that represents a session-persistent, document isolated, unique identifier that a developer can reliably use to identify individual pens interacting with the page.

[Read the complete [Explainer](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/PointerEventDeviceId/explainer.md)]. 

## Feedback

Please provide all feedback below.
[Explainer](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/PointerEventDeviceId/explainer.md) "Extending the PointerEvent with Unique DeviceId Attribute"

**Comment by Crissov** [comment]
Do you really want to distinguish multiple _users_ using a shared host device, or multiple _input devices_?

For touchscreen devices, would you want to distinguish different fingers, hands or people?

**Comment by sahirv** [comment]
Good questions! We want to distinguish input devices - namely devices that have an identifier that allows us to differentiate it from another device of the same kind; for example, a pen device. Of course, the id itself will not be fronted due to it being personally identifiable information. Explainer/security questionnaire in the TAG review will have more information on this.

_For touchscreen devices, would you want to distinguish different fingers, hands or people?_
No we won't be differentiating between fingers, hands, or people. A pointer event generated by finger will not have a valid device id, and a device id of 1 is reserved or mouse input. Other than that, the device id allocated to a device will not be able to identify what kind of device it is.

**Comment by sahirv** [comment]
@yoavweiss Now that we have demonstrated support for this, can we create a repository under WICG?

**Comment by sahirv** [comment]
Also adding the remaining chairs @cwilso @marcoscaceres @LJWatson in case Yoav is on vacation.

**Comment by RByers** [comment]
FWIW,  I'm supportive of this feature for Google Chrome. It's a very minor addition to pointer events. We don't have particular use cases that make it a priority for us, but I think it's very reasonable and, as designed, does not pose any additional privacy concern for us (really no different from the fact we already identify a mouse, stylus and touch separately). So +1 to a WICG repo for this (assuming Pointer Events WG still doesn't want to take it on directly yet).

**Comment by flackr** [comment]
Yes, this sounds good to me. I think the main issue to putting this in Pointer Events WG is that we're currently trying to finalize the level 3 spec, and this would be something we'd want to put in the next level.

**Comment by cwilso** [comment]
Sounds great.  This repo has been created, with the content from the explainer merged in: https://github.com/WICG/pointer-event-extensions.
