### ISSUE TITLE
ServiceWorker Static Routing API

### ISSUE THREAD

**Issue by yoshisatoyanagisawa** [WICG/proposals#102]
## Introduction

This API allows developers to configure the routing, and allows them to offload simple things ServiceWorkers do. If the condition matches, the navigation happens without starting ServiceWorkers or executing JavaScript, which allows web pages to avoid performance penalties due to ServiceWorker interceptions.

Starting ServiceWorkers is known to be a slow process, and web users need to wait for its startup if the ServiceWorker intercepts loading the page resources. At the same time, the ServiceWorker brings flexibility to the transport layer, and it behaves as a client-side proxy. Developers can implement offline support or provide client-side content modification with it. Currently, ServiceWorkers intercept all requests for pages within their scope, which brings a performance penalty within the scope.

## Feedback

Please provide all feedback below.
[Explainer](https://github.com/yoshisatoyanagisawa/service-worker-static-routing-api) "ServiceWorker Static Routing API"

**Comment by sisidovski** [comment]
Regarding this API, we see multiple interests from the developer community. e.g.
https://github.com/w3c/ServiceWorker/issues/1373#issuecomment-1667842174
https://bugs.chromium.org/p/chromium/issues/detail?id=1468239

**Comment by cwilso** [comment]
Sounds good.  @yoshisatoyanagisawa if you want to transfer the repo for the explainer to me, I can transfer it into the WICG org (you will keep admin rights).

**Comment by yoshisatoyanagisawa** [comment]
@cwilso Yes, please.  Thank you for the help.  Do I need to do something to make that happen?

**Comment by cwilso** [comment]
This has now been migrated into WICG: https://github.com/WICG/service-worker-static-routing-api.
