### ISSUE TITLE
IdentityCredential

### ISSUE THREAD

**Issue by RByers** [WICG/proposals#105]
## Introduction

There are multiple ways to present credentials on the web, and more being proposed. It may be that some use cases (like age verification or university affiliation) will be able to be met by multiple different approaches, but existing API designs could mean that users are forced to choose which technology to use without necessarily having the context to easily make that choice. Eg. websites might be forced to present options like "Click here to prove your employer with the identity in your wallet app" and "Click here to login to your company's server to prove your employment".

It seems there's an opportunity to create some common groundwork now which could help enable websites to more often simply say "Click here to prove your employer" and let the browser and OS figure out what options are best presented for this specific user.

We've had some early discussions around one such approach we call [IdentityCredential][explainer]. It's not yet clear if this is the best possible approach, or even if this problem definitely needs a solution. But we'd like to collect more thoughts on this space and so would like to move this proposal to the WICG for wider discussion.

## Feedback (Choose One)

I welcome feedback in this thread, but encourage you to file bugs against [the Explainer][explainer].

[explainer]: https://github.com/agl/identity-credential/blob/main/README.md "IdentityCredential Explainer"

**Comment by timcappalli** [comment]
Microsoft supports moving the IdentityCredential proposal into the WICG for wider discussion and incubation.

**Comment by RByers** [comment]
This has been moved here: https://github.com/WICG/identity-credential
