### ISSUE TITLE
Web Preferences API

### ISSUE THREAD

**Issue by lukewarlow** [WICG/proposals#117]
# Web Preferences API

## Introduction

The *Web Preferences API* aims to provide a way for sites to indicate a user preference for a given pre-defined setting (e.g. color-scheme preference) in a way that fully integrates with existing Web APIs.

[Read the complete Explainer](https://github.com/lukewarlow/web-preferences-api/blob/main/README.md). 

## Feedback (Choose One)

I welcome feedback in this thread, but encourage you to file bugs against [the Explainer](https://github.com/lukewarlow/web-preferences-api).

**Comment by lukewarlow** [comment]
I've made a very rough draft of a spec: https://specs.lukewarlow.dev/web-preferences-api/

**Comment by lukewarlow** [comment]
Idk if I count as a potential implementor? But I'm in the progress of making a start on a prototype in Chromium. Haven't filed an intent to prototype yet but working on it locally.

**Comment by yoavweiss** [comment]
> Idk if I count as a potential implementor?

If you're implementing, you're an implementer! :)

**Comment by lilles** [comment]
I'm generally positive. Unsure if navigator is the right place, and which spec it should live in. Currently looks like all values are MQ-related, but that might change?

Also, I'd have to think through the iframe behavior. The color-scheme behavior for things like iframes and embedded SVGs is somewhat complicated, and I'm unsure off-the-top-of-my-head how that would work with this API. But those details can be fleshed out.

This API would also be useful for devtools, which currently in Chromium-based browsers has a separate protocol for overriding media query values.

**Comment by yoavweiss** [comment]
Glad to see there's support for this! If you want to move this to WICG, feel free to transfer the repo to me and I can do the rest.

**Comment by bramus** [comment]
I’m personally very supportive of this proposal as it would allow authors to more easily implement Dark Mode Toggle Buttons without needing to duplicate parts of their CSS nor resort to blocking JS – a problem I’ve written about before, at https://www.bram.us/2022/05/25/dark-mode-toggles-should-be-a-browser-feature/

Very excited.

**Comment by lukewarlow** [comment]
@yoavweiss I've just requested a transfer to you :)

**Comment by yoavweiss** [comment]
The repo now lives at https://github.com/WICG/web-preferences-api

Happy incubating!!
