### ISSUE TITLE
Observable API

### ISSUE THREAD

**Issue by domfarolino** [WICG/proposals#118]
## Introduction

Event handling on the web platform is done imperatively, often with nested callbacks and a difficult-to-read flow of events. Observables offer a declarative, ergonomic, and composable way of handling events dispatched from an `EventTarget`.

[Read the complete Explainer][explainer]. 

## Feedback (Choose One)

I welcome feedback in this thread, but encourage you to file bugs against [the Explainer][explainer].

[explainer]: https://github.com/domfarolino/observable "Explainer Title"

**Comment by domfarolino** [comment]
I am working on a draft prototype of this API in Chromium, but have not yet sent an Intent to Prototype out. Does that count as enough support to begin to move this to WICG? @benlesh should be able to provide industry support for this proposal too.

**Comment by benlesh** [comment]
There is a lot of interest in this proposal from the community and from other library authors. Anecdotally:

1. A tweet linking this issue did quite well: https://twitter.com/BenLesh/status/1699460146219339785
2. More than one company has offered (unsolicited) sponsor my trip to TPAC to discuss this (I was paying out of pocket), for no other reason than they'd love to have it in the platform.
3. The initial issue on WHATWG got a lot of attention as well: https://github.com/whatwg/dom/issues/544#issue-281633681
4. A previous tweet about the repo with the proposal got a good amount of traction as well: https://twitter.com/domfarolino/status/1684921351004430336... which included a lot of [excitement from influential web developers and framework implementors including Svelte and SolidJS](https://twitter.com/domfarolino/status/1684921351004430336/retweets/with_comments)

**Comment by cwilso** [comment]
This seems like enough support to move into WICG org.  Feel free to transfer the repo to me and I will move it.

**Comment by domfarolino** [comment]
The repository has been moved to https://github.com/WICG/observable, so I think we can close this.
