### ISSUE TITLE
Web Printing API

### ISSUE THREAD

**Issue by GrapeGreen** [WICG/proposals#120]
## Introduction

The Web Printing API strives to improve the general printing experience with a primary focus on remote/virtual desktop systems by providing a standardized and seamless way for remote clients to interact with printers directly.

The proposed API methods unlock proper printer forwarding by allowing the remote client to access essential information about printers on the near side : this would eliminate the need for tedious manual configurations such as setting up virtual printers and excessive user interactions such as having to click through print job settings twice (once on the remote side & once locally) as well as encourage remote document rendering while tailoring to the capabilities of a particular printer.

[Read the complete Explainer](https://github.com/GrapeGreen/web-printing). 

## Feedback

I welcome feedback in this thread, but encourage you to file bugs against [the Explainer](https://github.com/GrapeGreen/web-printing).

**Comment by yoavweiss** [comment]
The repo now lives in https://github.com/WICG/web-printing

Happy incubating!!
