### ISSUE TITLE
Trusted Execution Environment Auction Servers for Protected Audience

### ISSUE THREAD

**Issue by itaysharfi** [WICG/proposals#122]
## Introduction

Trusted Execution Environment (TEEs) provide an execution environment that mitigates unauthorized access to user data. TEEs can run in the cloud and scale according to client execution and data serving needs. Recognizing these contributions, Protected Audience includes support for auction servers such as the Key Value (K/V) Server and the Bidding and Auction (B&A) services. 

## Use Cases (Recommended)

Example of K/V use-cases can be found in https://github.com/privacysandbox/fledge-docs/blob/main/key_value_service_use_cases.md

Overview of the Bidding and Auction server can be found in https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_services_api.md

## Goals

We would like to have a a dedicated forum to continue to incubate Auction TEEs towards the standard process.

## Non-goals (Optional)

Discussing general Protected Audience API, which we already have dedicated forum for. https://github.com/WICG/turtledove

## Proposed Solution

TEE based solutions to extend capabilities of auctions.

## Examples (Recommended)

Extend auction execution and serving of real time signals to the cloud.

**Comment by michaelkleber** [comment]
Heads up @thegreatfatzby and @erik-anderson: at TPAC'23 you were advocating for starting a separate WICG incubation space for TEE'd server stuff, which today we talk about as part of the [Protected Audience](https://github.com/WICG/turtledove/blob/main/FLEDGE.md) incubation.

Feel free to speak up here, so that we have a second demonstration of interest.

**Comment by thegreatfatzby** [comment]
[Second](https://youtu.be/_OemNp6hgX4).

**Comment by michaelkleber** [comment]
Okay, with support from both Google and Microsoft, we should do this.

Itay, next step is for you to transfer ownership of the repo https://github.com/privacysandbox/fledge-docs to a WICG Chair like @yoavweiss, who can then move the repository into WICG.

**Comment by cwilso** [comment]
Yep yep.  Transfer it either to Yoav or myself, and we can move it into WICG.
