### ISSUE TITLE
Device Attributes API

### ISSUE THREAD

**Issue by Ananubis** [WICG/proposals#14]
## Introduction

It is a common requirement for operating systems to be able to provide applications with the highest degree of trust access to the highly-priviliged data/functions. One of the popular requirements in the commercial systems is the ability for a highly-trusted  application to access device-identification information(serial number, asset it). This API tries to bring this ability to the Web, although restricting it to a small configurable subset of highly trusted applications.

[Read the complete Explainer](https://github.com/Ananubis/WebApiDevice/blob/master/Explainer.md#device-attributes). 

## Feedback
I welcome feedback in this thread, but encourage you to file bugs against [the Explainer](https://github.com/Ananubis/WebApiDevice/blob/master/Explainer.md#device-attributes).

**Comment by mattdh250** [comment]
Thank you for this API proposal and explainer.

Signagelive require this API as we migrate our Digital Signage Media Player from a Chrome App to a PWA so that we can get the device directory id. We use this Id to uniquely identify all Chrome devices that connect to our platform.

**Comment by creinhard** [comment]
Thank you for the proposal! Wondersign will also require this API to migrate our Catalog Kiosk App form Chrome App to PWA. 

**navigator.device.getDirectoryId()**
Being able to get the directory id will allow us to migrate devices from Chrome App to PWA without user interaction.

**navigator.device.getSerialNumber()**
Being able to get the device's serial number will help us to physically identify devices and help support customers with hardware issues.

**Comment by divyacitrix** [comment]
Citrix needs this API for device hardware ID to identify the device, as our license is user-device specific.So getting userID from OAuth alone wont be enough.
Currently we are generating random number and storing in local storage but this is not reliable as on 'clearData' of the site this goes away.

**Comment by yoavweiss** [comment]
The repo is now at https://github.com/WICG/WebApiDevice
Happy incubating!!

**Comment by mong8se** [comment]
This api is also vital to our efforts to transition to PWA for thousands of production kiosks-mode devices in an enterprise environment. We need to be able to securely track and identify these devices to manage and orchestrate them with our tools.

**Comment by divyacitrix** [comment]
A followup to my comment above. Specifically we'd need hostName and AssetId to meet our application's needs.
