### ISSUE TITLE
Remove recommendation to use Discourse

### ISSUE THREAD

**Issue by autonome** [WICG/proposals#148]
The readme has the following:

> We continue to recommend that our community participate in Discourse for less well-formed ideas to germinate, for early explorations, and for other discussions. As these ideas, explorations, and discussions mature, they may form into a proposal which should then be filed as an issue in this repo.

However, the Discourse does not seem to be serving this purpose, as the most recent post is from nearly six months ago, and most of 2023 saw very little activity since the move here:

![CleanShot 2024-04-25 at 10 22 07@2x](https://github.com/WICG/proposals/assets/50103/37212166-442c-467a-b67e-753d3c46236b)

While reviewing the proposals here, the pattern seems to be that the discussions previously happening on Discourse are now happening here in the comments on proposals.

This means there's a participation barrier: A quick glance tells a newcomer that nobody's looking at Discourse but people are participating here. However this repo is only for "well-formed ideas".

My $0.02: Acknowledge the pattern and "be where the people are" by removing the recommendation to continue using Discourse and instead allow ideas to form well (or not) here.

**Comment by marcoscaceres** [comment]
Agree.. plus our Discourse instance has been archived. I don't think anyone can add to it. Sent a PR
