### ISSUE TITLE
Document Policy

### ISSUE THREAD

**Issue by clelland** [WICG/proposals#15]
## Introduction

This was originally [proposed on Discourse](https://discourse.wicg.io/t/proposal-document-policy/4483), but this seems to be the new place for proposals.

Document Policy is a configuration mechanism for the web platform, allowing site authors (for instance) to enable or disable the use of platform APIs, improve their performance by setting thresholds for the sizes or efficiency of images, or sandbox individual frames.

It has split from Feature Policy, as a means of configuring features other than permissions, and so currently lives in a W3C WebAppSec WG repo. The spec is already in progress there, but the consensus of the WG is that it should be incubated at WICG while it is completed, and while we gather implementer interest.

[Read the complete Explainer](https://github.com/w3c/webappsec-permissions-policy/blob/master/document-policy-explainer.md) or the [spec](https://w3c.github.io/webappsec-permissions-policy/document-policy.html)

Document Policy is [under review by TAG](https://github.com/w3ctag/design-reviews/issues/408).
It has been partially [shipped in Chrome](https://www.chromestatus.com/feature/5645593894453248) to [support](https://www.chromestatus.com/feature/5744681033924608) the "[Scroll-to-text-fragment](https://github.com/WICG/scroll-to-text-fragment)" feature.

## Feedback (Choose One)

Please provide all feedback below.

**Comment by clelland** [comment]
This move was originally suggested by Mozilla folks (https://github.com/w3c/webappsec-permissions-policy/issues/411 most recently, but it had been discussed previously).

Moving to WICG was also discussed in WebAppSec WG meetings in May ([minutes](https://github.com/w3c/webappsec/blob/master/meetings/2020/2020-05-19-minutes.md)) and then again in November ([minutes](https://github.com/w3c/webappsec/blob/master/meetings/2020/2020-11-17-minutes.md)) because I had forgotten about it :)

**Comment by yoavweiss** [comment]
Seems like there's enough support for the move to WICG. Do you have a repo you want to move, or should we create a new one?

**Comment by clelland** [comment]
It currently lives within the w3c/webappsec-permissions-policy repo, as it split off of that spec, but we shouldn't move the whole repo. Probably best to create a new one, and migrate the relevant issues.

**Comment by yoavweiss** [comment]
I've spun up https://github.com/WICG/document-policy and gave you access.

Happy incubating!

**Comment by clelland** [comment]
Thanks!

**Comment by yoavweiss** [comment]
Let's leave this open to keep track of the proposal through its lifecycle (so, until it graduates to a WG)

**Comment by clelland** [comment]
SGTM. (I thought this was more a "proposal to open a new repo" rather than "proposal for a new API")
