### ISSUE TITLE
Canvas Place Element

### ISSUE THREAD

**Issue by fserb** [WICG/proposals#167]
## Introduction

This proposal covers APIs to allow live HTML elements on Canvas 2D, WebGL and WebGPU.

[Read the complete Explainer][explainer]

## Feedback

Please provide all feedback below.

I welcome feedback in this thread, but encourage you to file bugs against [The Explainer][explainer]

Here is the relevant portion of the [CSSWG F2F log from June 12th](https://logs.csswg.org/irc.w3.org/css/2024-06-12/#e1628190)) discussing the issue and showing support from multiple vendors.

[explainer]: https://github.com/fserb/canvas-place-element

**Comment by cwilso** [comment]
With the broad support from the CSSWG F2F log, this has been moved in: https://github.com/WICG/canvas-place-element.
