### ISSUE TITLE
Forms lack basic functionality

### ISSUE THREAD

**Issue by alejsanc** [WICG/proposals#26]
As I have expressed in some proposals that I have sent, the forms have very little functionality, they have hardly evolved and it would be necessary to carry out a study on their present and future.

[Form submission in the background without Javascript](https://github.com/WICG/proposals/issues/25)

[Form submission does not show progress](https://github.com/WICG/open-ui/issues/279)

[Form not submitted warning message before unload](https://github.com/WICG/open-ui/issues/280)

[Form submission confirmation without Javascript](https://github.com/WICG/open-ui/issues/281)

[Change form "action" attribute to "target" and add "action" attribute to buttons](https://github.com/WICG/proposals/issues/126)

[Groups of inputs and arrays of groups of inputs in forms](https://github.com/WICG/proposals/issues/132)

[Add boolean input element with "true" and "false" values](https://github.com/WICG/proposals/issues/27)

[Null value in file input](https://github.com/WICG/proposals/issues/135)

[Add method to reset file input and show file size and image/video/audio preview](https://github.com/WICG/proposals/issues/134)

[Add "type" attribute to "textarea" element](https://github.com/WICG/proposals/issues/136)

[Change URL parameter without Javascript](https://github.com/openui/open-ui/issues/276) or [Add a new element to change a URL parameter without Javascript](https://github.com/openui/open-ui/issues/666)

[Searchable dynamic datalist with JSON list without Javascript](https://github.com/WICG/proposals/issues/23)

[Add a new input type for verification codes](https://github.com/openui/open-ui/issues/777)

**Comment by LJWatson** [comment]
Thanks @alejsanc. This seems to be a round-up of proposals, rather than a proposal in its own right, so we're closing it here.

**Comment by alejsanc** [comment]
> Thanks @alejsanc. This seems to be a round-up of proposals, rather than a proposal in its own right, so we're closing it here.

This is a proposal to make an extensive and necessary evolution of the forms. Each of the proposals included is a part of this evolution. All proposals are related and must be studied together. That is why this proposal that brings them together makes sense.
