### ISSUE TITLE
Compute Pressure API

### ISSUE THREAD

**Issue by oyiptong** [WICG/proposals#28]
## Introduction

Web applications are today being used to provide a wide range of solutions,  including some use-cases that push the capabilities of the device they are running on, e.g. video gaming and video-conferencing.

It is a testament to the web's power as a platform that one application will run on devices ranging from low-powered devices all the way to the most powerful machines.

However, a one-size-fits all approach does not work well for computational intensive applications; a missing capability of the web is to allow developers to tailor the experience depending on computational capacity.

Compute-intensive web apps that want to provide a good experience across their user base rely on browser extensions to access system metrics.

The Compute Pressure API will let developers write web applications that anticipate and react to system load changes to provide a great experience for users regardless of their device's compute prowess.

[Read the complete Explainer][explainer]. 

## Feedback (Choose One)

I welcome feedback in this thread, but encourage you to file bugs against [the Explainer][explainer].

[explainer]: https://github.com/oyiptong/compute-pressure/blob/main/README.md "Compute Pressure"

**Comment by arnaudbud** [comment]
RingCentral is very keen to have the Compute Pressure API generally available, especially to enhance the end-user experience on resource constrained devices.

**Comment by rezaulakram** [comment]
Compute Pressure API will be helpful in improving the overall user experience of Stadia and provide better streaming quality on resource constrained systems.

**Comment by yoavweiss** [comment]
Given support, the repo now lives at https://github.com/WICG/compute-pressure
Happy incubation!!
