### ISSUE TITLE
User Preference Media Features Client Hints Headers

### ISSUE THREAD

**Issue by tomayac** [WICG/proposals#30]
## Introduction

HTTP Client Hints defines an `Accept-CH` response header that servers can use to advertise their use of request headers for proactive content negotiation. This proposal introduces a set of user preference media features client hints headers like `Sec-CH-Prefers-Color-Scheme`, which notify the server of user preferences that will meaningfully alter the requested resource, like, for example, through the currently preferred color scheme. These client hints will commonly also be used as critical client hints via the `Critical-CH` header.

Read the complete [Explainer](https://github.com/tomayac/user-preference-media-features-headers/blob/main/README.md) or the [spec draft](https://tomayac.github.io/user-preference-media-features-headers/). 

## Feedback

We welcome feedback in this thread, but encourage you to file bugs in the [repo](https://github.com/tomayac/user-preference-media-features-headers).

**Comment by larsroettig** [comment]
I like the excellent proposal explainer very clearly aligned with the PWA goals.

From my perspective, a header for a colorblind (Tritanopia, Deuteranopia, Protanopia) person could increase usability. But maybe this is going too far, especially for government websites.

**Comment by tomayac** [comment]
Thanks for the supportive feedback. 

> [A] header for a color-blind (Tritanopia, Deuteranopia, Protanopia) person could increase usability.

From my experience, people with special needs are not fond of these special needs to be exposed to websites.

It’s too easy to _(i)_ be given special treatment by well-meaning developers (meant well is usually the opposite of good) in the best case (e.g., a dumbed down version of the site), or _(ii)_ be targeted by advertisers and be put in a special category in the worst case.

People with such conditions tend to deal with this at the OS level ([macOS example](https://support.apple.com/guide/mac-help/change-color-filters-preferences-mchlba06b669/mac)).

**Comment by nirsharma** [comment]
It definitely helps SSR apps to early assess user preference.

For example, currently SSR apps have to use **media features** on the client to evaluate whether user wants dark-mode or night mode. With these headers we can serve them dark/light pages(assets) from server itself.
This improves user-experience.

**Comment by n8schloss** [comment]
Just wanted to chime in to say that a few teams at Facebook expressed interest in this, so we'd love to see progress on these APIs :)

**Comment by yoavweiss** [comment]
The repo is now live on https://github.com/WICG/user-preference-media-features-headers
Happy incubating!!

**Comment by tomayac** [comment]
Thanks, @yoavweiss! Is the process now for us to close this present Issue, or do we leave it open until, erm, `$something` happens?

**Comment by yoavweiss** [comment]
We can leave it open to keep track of the proposal as it progresses

**Comment by tomayac** [comment]
To close the loop on this: we have [introduced the `Sec-CH-Prefers-Color-Scheme` header](https://web.dev/user-preference-media-features-headers/) as a first specimen of other user preference media feature headers. Thanks everyone for their feedback and helpful remarks on this issue. Closing.
