### ISSUE TITLE
Add preferCurrentTab to getDisplayMedia

### ISSUE THREAD

**Issue by eladalon1983** [WICG/proposals#32]
## Introduction

Sites often wish to self-capture. For example, a slides deck application might wish to let the user stream the presentation to a virtual conference.

Calling getDisplayMedia offers the user a wide selection of possible capture-sources. What if the application really just wants the current tab? It could be hard for the user to hunt down the specific tab out of all the tabs they have open.

Ideally, the application would be able to present a confirmation-only dialog to the user - share the current tab, yes/no? Standardization efforts for this feature as [getViewportMedia](https://github.com/w3c/mediacapture-screen-share/pull/148) are underway.

However, [getViewportMedia](https://github.com/w3c/mediacapture-screen-share/pull/148) will be gated by (1) cross-origin isolation and (2) an opt-in header. That will limit adoption, at least initially.

We therefore extend [getDisplayMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) in a way that allows the application to inform the browser that it prefers the current tab. [getDisplayMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) currently accepts a single parameter of type [MediaStreamConstraints](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints) (a dictionary). We extend that dictionary with a new member called preferCurrentTab. This new member is a boolean defaulting to false. When set to true, the browser presents the current tab as the most prominent option.

![Screen Shot 2021-06-09 at 15 29 40](https://user-images.githubusercontent.com/22117736/121363947-a6937d00-c937-11eb-8594-ce35d3252e50.png)

This is an imperfect solution; a compromise between two needs:
* Applications need a way to signal preference for the current tab. Possibly even exclusive need of the current tab.
* [getViewportMedia](https://github.com/w3c/mediacapture-screen-share/pull/148) is a long way off, and the security requirements gating it will need a long time to gain widespread adoption.

## Feedback (Choose One)

Please provide all feedback below.

Explainer: [preferCurrentTab - Explainer](https://docs.google.com/document/d/1Og-TUBJQ4SAgReBr7xrd7y-0ZwkjGJMCqBnzDv7_-vs/edit?usp=sharing)

**Comment by murillo128** [comment]
I definitely support this api.

The use case of allowing a web page to stream its content to a webrtc service for streaming is really interesting, expecialy when [WHIP](https://datatracker.ietf.org/doc/html/draft-murillo-whip-02) is finalized and we can have a common ingest protocol for all webrtc services.  

As an example of this use case, jitsi currently allows to broadcast a conference by configuring an rtmp url:
![image](https://user-images.githubusercontent.com/1070835/121385859-c633a100-c949-11eb-89e0-cd98fd75cf8d.png)

This requires the mixing to do server side as there is no way of performing rtmp publish on a web page, but with WHIP and this api it could be able to do it on the client side, freeing resources on the server side and allowing  for example to keep end to end encryption.

As a sub case of this, it would be very interesting to have this API without any user prompt for automation purposes (enabled via a command line flag or similar)

**Comment by eladalon1983** [comment]
Thanks, @murillo128!
For automation purposes, I believe [these flags](https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/chrome_switches.cc;l=549-552;drc=3bfd3ba3af617152dfee61d03e93a773ddd3443b) should do the trick for you. Let me know if more is required.

**Comment by murillo128** [comment]
Yes, I am using those flags, would be great if they keep working with the api changes.

**Comment by eladalon1983** [comment]
They will keep working.

**Comment by eladalon1983** [comment]
P.S: This has been implemented and is available as on origin-trial starting with Chrome m90. A [demo](https://eladalon1983.github.io/gcbcm-demo/) is available.

**Comment by yoavweiss** [comment]
The repo now lives in https://github.com/WICG/prefer-current-tab
Happy incubation!! :)

**Comment by arnaudbud** [comment]
We at [RingCentral](https://www.ringcentral.com/) think this would be useful to us.

**Comment by emcho** [comment]
This looks good and I find it could prove useful to the [Jitsi Meet](https://jitsi.org) app suite. Thanks for doing the work!

**Comment by zoomienick** [comment]
Definitely interested in seeing this implemented at Zoom. Thanks for the effort!

**Comment by BrennanColberg** [comment]
+1 from [Synthesis](https://synthesis.is), this would be fantastic.

**Comment by eladalon1983** [comment]
This shipped in Chrome in m94.
[Chrome Status entry](https://chromestatus.com/feature/5045313003847680)
[Specification](https://wicg.github.io/prefer-current-tab/)
