### ISSUE TITLE
Interactive Video

### ISSUE THREAD

**Issue by AdamSobieski** [WICG/proposals#33]
## Introduction

[_Interactive videos_](https://en.wikipedia.org/wiki/Interactive_video) are videos which support user interaction. Interactive videos can navigate to, or branch to, video content depending upon: users’ interactions with menus, users’ settings and configurations, models of users, other variables or data, random numbers, and program logic.

Educational uses of interactive video include, but are not limited to: instructional materials, how-to videos, and interactive visualizations.

Some chatbots or dialogue systems can be stored as interactive videos.

[_Interactive films_](https://en.wikipedia.org/wiki/Interactive_film) are interactive videos or cinematic videogames where one or more viewers can interact to influence the courses of unfolding stories. Interactive films can be described as video forms of [choose-your-own-adventure](https://en.wikipedia.org/wiki/Choose_Your_Own_Adventure) stories, or [gamebooks](https://en.wikipedia.org/wiki/Gamebook). Contemporary examples of interactive films include: “Black Mirror: Bandersnatch”, “Puss in Book: Trapped in an Epic Tale”, and “Minecraft Story Mode”.

One day, some AI systems could be trained using large collections of interactive films.

## A Standard Runtime Environment

As envisioned, interactive videos contain JavaScript scripts and/or WebAssembly (WASM) modules. These scripts and modules should be provided with a runtime environment different from the one provided by Web browsers for Web documents. The runtime environment provided for interactive video scripts and modules should include functionality for:

1. navigation (e.g., seeking to clips, segments, or chapters in interactive videos)
2. prefetching resources (e.g., files in videos, or video attachments)
a. there should be a way, e.g., using URL fragments, to locate and prefetch files in videos, or video attachments
3. opening resources (e.g., files in videos, or video attachments)
a. there should be a way, e.g., using URL fragments, to locate and retrieve files in videos, or video attachments
4. presenting menus
a. perhaps also functionality for presenting image maps or “hotspots” atop video
5. accessing users’ settings and configurations
6. storing and accessing local data
7. storing and accessing remote data
a. e.g., learner, player, and user models
8. parsing JSON, XML, RDF, and other data formats

There is a need for one standard runtime environment for use by multiple interactive video formats. With a standard runtime environment, interactive video player software (e.g., Web browsers) could more readily play multiple formats of interactive video.

## Security Considerations and User Permissions

Only the standard runtime environment intended for interactive videos’ JavaScript scripts and WASM modules should be available to them. Containing documents could, perhaps, permit otherwise (see also: `<iframe>`).

Interactive videos could contain hashes for and/or digital signatures of files in videos, or video attachments. WASM modules could be digitally signed.

Interactive video players (e.g., Web browsers) could make use of user permissions systems to protect users’ data privacy while providing users with features.

## Menus and Accessibility

As envisioned, the presentation and display of menus is handled by interactive video players through the runtime environment API. Menus could be presented to users by invoking a `present` function.

```
Promise<MenuReponse> present(any menu, optional any options);
```

## Spoken Language Interaction and Dialogue Systems

Interactive videos could utilize speech recognition grammars (e.g., SRGS) to enable users to select menu options via spoken natural language. In Web browsers, this functionality could be provided via the Web Speech API.

Perhaps interactive videos could also utilize remote speech recognition services.

## Internationalization

Different versions of files in videos, or of video attachments, could exist in interactive videos for specific languages (e.g., menus, speech recognition grammars).

## Documents Containing Interactive Videos

A document element for interactive video (e.g., `<video>`) could have an event upon its interface to be raised whenever a menu is to be presented to a user. In this way, the presentation of a menu could be intercepted by a containing document. The containing document could then process the arguments passed to the `present` function, display a menu to a user in a stylized manner, and provide a response back to the interactive video’s scripts or WASM modules, for example resulting in navigation to, or seeking to, a video clip, segment, or chapter.

## Interactivity via Animated Colored Silhouettes in Secondary Video Tracks

One could use secondary video tracks to provide arbitrarily-shaped interactive regions. These secondary video tracks could each contain multiple animated colored silhouettes, overlay regions, or “hotspots”. The colors of these silhouettes would correspond with arbitrarily-shaped interactive elements. The color black, however, would be reserved for indicating the absence of a silhouette.

Consider an interactive video of an automobile engine, under a hood. Envision a secondary video track where there is a colored silhouette for each part of the engine. While the primary video track would be visible to a user, using the secondary video track(s), the user could, with their mouse, hover over and click on the parts of the engine.

Animated colored silhouettes could also be rectangular and mirror the motion of text or images in videos. This would facilitate traditional hyperlinks in videos.

## Semantics and Metadata

With semantics and metadata, one could describe the contents of videos, the objects and events which occur in them, and place this information in semantic tracks. One could utilize semantic graphs as well as “semantic deltas”, or “semantic diffs”, which indicate instantaneous changes to semantic graphs.

As envisioned, the animated colored silhouettes in secondary video tracks have unique identifiers and are URI-addressable. In this way, semantics and metadata could more readily describe the silhouetted regions which map to visual contents in videos.

With semantic tracks, users could, for example, utilize queries, via user interfaces, upon the contents of videos and observe the query results, e.g., objects or events, visually selected, outlined, or highlighted in the videos. Also possible is that query results could be presented to users with storyboards or other visualizations using relevant images from videos.

## JavaScript and WebVTT

A syntax example is indicated for embedding JavaScript in WebVTT text tracks. The example provides two lambda functions for a cue, one to be called when the cue is entered and the other to be called when the cue is exited.

```
05:10:00.000 --> 05:12:15.000
enter:()=>{...}
exit:()=>{...}
```

## Polyfills and Prototyping

It appears that to implement a polyfill to prototype interactive video functionality, the HTML5 media API would need to surface the capability to access files in videos, or video attachments.

As envisioned, a polyfill would load JavaScript scripts and WASM modules from videos, implement and provide the standard runtime environment for those scripts and modules, and then run the videos, e.g., perhaps by calling a function like `main` or raising an event.

Another approach could make use of HTML5 custom elements. A custom element:

```
<custom-ivideo src="X" />
```

could utilize an `<iframe>` to load a generated HTML5 document:

```
<iframe src="ivideo.php?src=url_encode(X)" allowfullscreen="true" />
```

with that generated HTML5 document resembling:

```
<html>
  <head>
    <script src="ivideo-polyfill.js" />
  </head>
  <body>
    <video src="X" />
  </body>
</html>
```

This could also be achieved utilizing the `srcdoc` attribute of the `<iframe>` element.

## Attachments
Attachments in videos are additional files, such as "related cover art, font files, transcripts, reports, error recovery files, picture or text-based annotations, copies of specifications, or other ancillary files".

One can refer to a [comparison of video container formats](https://en.wikipedia.org/wiki/Comparison_of_video_container_formats#General_information) to see which video container formats presently support attachments.

Attachments in videos are a means for adding JavaScript scripts and WASM modules to videos. By placing utilized scripts and modules in interactive videos, the videos can be self-contained and portable.

Interfaces for inspecting and accessing attachments could resemble:
```
partial interface HTMLMediaElement
{
  [SameObject] readonly attribute AttachmentList attachments;
}
```
```
[Exposed=Window]
interface AttachmentList : EventTarget {
  readonly attribute unsigned long length;
  getter Attachment (unsigned long index);

  attribute EventHandler onchange;
  attribute EventHandler onaddattachment;
  attribute EventHandler onremoveattachment;
};
```

In theory, one could provide arguments including MIME type and natural language when opening a video attachment, per 
[content negotiation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation).
```
partial interface AttachmentList
{
  Attachment? getAttachment(DOMString name, optional DOMString type, optional DOMString lang);
}
```
or
```
partial interface AttachmentList
{
  Promise<Attachment?> getAttachment(DOMString name, optional DOMString type, optional DOMString lang);
}
```
for example `getAttachment("main", "application/wasm")`.

Related specifications include the [File API](https://www.w3.org/TR/FileAPI/) and [`BufferSource`](https://heycam.github.io/webidl/#BufferSource). The `BufferSource` interface is utilized for [loading WASM modules](https://webassembly.github.io/spec/js-api/index.html#webassembly-namespace).

Alternatively, mechanisms for inspecting and accessing video attachments could be encapsulated by Web browsers and the standard runtime environment for interactive video.

## Conclusion

A standard runtime environment for interactive videos and standard formats for interactive videos are needed. With new standards, interactive videos would be readily authored, self-contained, portable, secure, accessible, interoperable, readily analyzed, and readily indexed and searched.

There is a need for one standard runtime environment for use by multiple interactive video formats. With a standard runtime environment, interactive video player software (e.g., Web browsers) could more readily play multiple formats of interactive video.

With standard interactive video formats (and perhaps open file formats for project files), extensible content authoring tools could be more readily developed. Authoring interactive stories and producing interactive films is difficult and, with new software tools, we could expect much more content.

With standard interactive video formats, interactive videos would be self-contained and portable.

With a standard runtime environment and standard interactive video formats, interactive videos would be more secure and would access user data and other resources only in accordance with user permissions.

With a standard runtime environment and standard interactive video formats, interactive videos would be accessible.

With standard interactive video formats, interactive videos would be interoperable with other technologies. For example, interactive videos could be played in Web documents and EPUB digital textbooks.

With standard interactive video formats, interactive videos could be better analyzed.

With standard interactive video formats, large collections of interactive videos could be better indexed and searched.

Thank you. I look forward to discussing these ideas with you.

## References
[HTML5 Media] https://html.spec.whatwg.org/multipage/media.html
[PLS] https://www.w3.org/TR/pronunciation-lexicon/
[SMIL] https://www.w3.org/TR/SMIL/
[SRGS] https://www.w3.org/TR/speech-grammar/
[V8] https://v8.dev/
[V8 Isolates, Contexts, Worlds and Frames] https://chromium.googlesource.com/chromium/src/+/refs/heads/main/third_party/blink/renderer/bindings/core/v8/V8BindingDesign.md#A-relationship-between-isolates_contexts_worlds-and-frames
[WASM] https://webassembly.org/
[Web Animations] https://www.w3.org/TR/web-animations-1/
[Web Speech API] https://wicg.github.io/speech-api/
[WebVTT] https://www.w3.org/TR/webvtt1/

**Comment by spaceribs** [comment]
I'm the developer of a web extension called [Plopdown](https://plopdown.video/) which adds interactive elements to existing videos on the web. The most complex and annoying problem in this space is the calculations and updates I need to make to ensure the elements related to the video are positioned correctly and show up in fullscreen. If anything should come out of this proposal, it's the ability to add elements to the playing video that are fully embedded.

**Comment by AdamSobieski** [comment]
@spaceribs , thank you. I wonder whether Plopdown uses rectangular regions for interactive elements or whether it utilizes arbitrary shapes?

On the topic of ways of implementing arbitrary shapes, in theory, one could use video tracks. These video tracks could contain multiple dynamic overlay regions or “hotspot” shape animations. Consider a video of a jet engine rotating and then consider another video track which could be visualized as having multiple colored blobs, these blob shapes overlaying with arbitrary regions atop the video of the jet engine. Each color would correspond with, or map to, an interactive element.

**Comment by spaceribs** [comment]
For plopdown, regions were somewhat restrictive and I specifically wanted to implement other kinds of overlays like picture-in-picture, games, etc. The best course of action was to use VTT metadata to store the rendering information and place an absolutely positioned `<div>` with a renderer which listens to the stream.

The tricky part was the positioning of the "stage" element. Originally I placed it as a sibling of the video, but the controls of Youtube/Netflix would prevent click events from coming through to my menus and elements. I eventually landed on querying via [elementsFromPoint](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementsFromPoint) as the best solution to make sure the overlay displayed in fullscreen.

**Comment by chrisn** [comment]
There's some similarity here with BBC R&D's object based media: https://www.ibc.org/trends/object-based-media-exploring-the-user-experience/6889.article

**Comment by AdamSobieski** [comment]
@chrisn , I approached these interactive and adaptive media topics from an AI and educational technology perspective. Thanks for that article which showcases some BBC R&D work and brings interesting journalism scenarios to mind.

**Comment by pchampin** [comment]
@AdamSobieski @spaceribs the [Media WG](https://www.w3.org/media-wg/) is currently being rechartered. Have a look at the [proposed charter](https://www.w3.org/2021/05/charter-media-wg.html), I think some of the deliverables will address several of the points raised above.

**Comment by chrisn** [comment]
It would be interesting to see a gap analysis:
- what can be done today using existing browser capabilities, by building a player library?
- what new browser capabilities are needed (taking into account current developments in the Media WG)?
- what APIs would a standardized interactive video player need to provide, built on top of those capabilities?

**Comment by Malvoz** [comment]
These proposals also seem related:
- Bullet Chatting: https://w3c.github.io/danmaku/
- Web Video Map Tracks Format (WebVMT): https://w3c.github.io/sdw/proposals/geotagging/webvmt/

**Comment by AdamSobieski** [comment]
@pchampin , @chrisn , thank you. I would like to propose adding the discussion and exploration of interactive video, branching video, interactive film, and related topics to the [new Media WG charter](https://www.w3.org/2021/05/charter-media-wg.html).

> * what can be done today using existing browser capabilities, by building a player library?

Using existing browser capabilities, polyfills, prototypes, or player libraries appear to require the capability to inspect and access file attachments in videos, to access the JS scripts and WASM modules in self-contained and portable interactive videos.

> * what new browser capabilities are needed (taking into account current developments in the Media WG)?

With respect to what new browser capabilities are needed, these include:

1. JavaScript and WebAssembly in Interactive Videos
a. Means of inspecting and accessing JS scripts and WASM modules in interactive videos (and attachments in general) could be provided to Web developers either: (1) by extending HtmlMediaElement, or (2) by implementing this functionality natively in browsers and then providing relevant API to interactive videos through the standard runtime environment for interactive videos.
2. Secure Runtime Environment
a. Placing interactive videos in secure `<iframe>`-like sandboxes can ensure that the JS scripts and WASM modules in them only have access to the standard runtime environment. It would be useful for browsers to be able to provide secure `<iframe>`-like environments for interactive videos without the scripting environments provided for Web documents and, instead, with the standard runtime environment for interactive videos.
3. Secondary Video Tracks
a. While playing and displaying primary video tracks, browsers should also be able to process synchronized secondary video tracks, e.g., containing one or more layers of colored silhouettes.
b. Ensuring that these silhouettes have unique identifiers, or are URI-addressable, might require some new video formats or other innovative techniques.
c. Web developers might desire to have some JavaScript APIs for these new tracks and related scenarios: (1) to inspect and access the set of currently visible silhouettes, to listen to events on this dynamic collection, and to listen to UI events on individual silhouettes, (2) to obtain bitmaps of silhouettes, to perform some operations on these, and to perform compositing with the visual contents of primary video tracks, e.g., to explore custom highlighting, visual outlines, and other custom effects.

> * what APIs would a standardized interactive video player need to provide, built on top of those capabilities?

With respect to what APIs that a standardized interactive video player would need to provide, there are two perspectives to consider. Firstly, the _Web document perspective_, where one can envision events such as `onmenu` for when interactive videos present users with menus. Secondly, the _interactive video perspective_, which is referred to, above, as the standard runtime environment, the APIs available to the JS scripts and WASM modules in interactive videos.

Possible features for the standard runtime environment include: navigation (seeking/branching), prefetching and opening video attachments, prefetching and opening remote resources, presenting menus, accessing users’ settings and configurations, storing and accessing local and remote data, parsing JSON, RDF, XML, and other data formats.

**Comment by AdamSobieski** [comment]
@Malvoz, thank you. Combining video annotation with video semantics (e.g., via ancillary or secondary video tracks with one or more layers of uniquely-identifiable silhouettes), end-users could annotate any objects, events, or activities occurring in videos, instead of annotating entire videos or timespans occurring in videos.

Hypertext visualizations of, or presentations of, annotations could follow or track objects, events, or activities in videos. This content could also position itself dynamically on screen in response to UI events.

There are interesting educational applications and scenarios to consider with respect to the combination of video semantics and video annotation.

**Comment by chrisn** [comment]
> @pchampin , @chrisn , thank you. If the topics aren't already in scope, I would like to propose adding the discussion and exploration of interactive video, branching video, interactive film, and related topics to the [new Media WG charter](https://www.w3.org/2021/05/charter-media-wg.html).

The Media WG is focused on standardising the specs listed in its charter, so probably isn't the best forum for exploratory discussion - the [Media & Entertainment Interest Group (MEIG)](https://w3.org/groups/ig/me) is better suited. That said, if any of your requirements would need changes to any of the Media WG specs, those could be raised as issues in the relevant GitHub repos.

**Comment by LJWatson** [comment]
@AdamSobieski, @chrisn, was there any further action with the MEIG and/or filing issues as Chris suggested?

**Comment by AdamSobieski** [comment]
@LJWatson, hello. I remain interested in these interactive video topics, e.g.:

1. video capable of displaying interactive elements, e.g., menus, atop it,
2. branching video where paths could be selected including based upon user interactions,
3. streaming video where content might be routed to or generated on-the-fly, including in response to user interactions.

I remain interested in brainstorming and discussing how these scenarios could be supported in Web browsers in standard ways, e.g., simply by using the `<video>` element. It may also be the case that WebRTC technologies could be of use for delivering interactive video scenarios...

**Comment by chrisn** [comment]
There hasn't really been much further discussion on this issue, at least in a W3C context, and MEIG would still welcome input in its GitHub repo.

BBC R&D continues to do work in this area, see for example some of our [pilots](https://www.bbc.co.uk/taster/) and [collaborations](https://ai4me.surrey.ac.uk/research.html).

**Comment by LJWatson** [comment]
Thanks @AdamSobieski and @chrisn. We'll need implementor interest to be able to move this forward, but before then I think the idea itself will need to be specified a bit more.

**Comment by AdamSobieski** [comment]
Thank you, @LJWatson, that makes sense to me. In response, I have opened a brainstorming thread in the Civic Technology Community Group mailing list.

I, for one, am excited about possibilities pertaining to the Web, smart TV, and new user experiences. For examples, while watching television, e.g., news content, I think: "what if consumers could check their local weather forecast at any point in time while remaining on a 'channel' of news content", and "what if I could open a grid-based navigation for multiple parallel streams inside of one 'channel' of content", and "what if news content could be semi-personalized, offering consumers more of what they want, less of what they want to avoid, while news providers could interrupt to provide breaking news content intended for entire audiences."

After brainstorming and discussing with the group, towards specifying interactive video ideas a bit more, I am looking forward to providing an update here or in the MEIG repository.

**Comment by chrisn** [comment]
@AdamSobieski Can I suggest we continue the discussion on these issues in the https://github.com/w3c/media-and-entertainment repo? MEIG is a good home for this kind of exploratory discussion for media related topics and doing gap analysis, then we can bring specific or concrete proposals to WICG.

**Comment by AdamSobieski** [comment]
Thank you. Sounds good!
