### ISSUE TITLE
Scripting Policy.

### ISSUE THREAD

**Issue by mikewest** [WICG/proposals#36]
## Introduction

XSS is bad. CSP's syntax is obtuse, and it's trying to do too many things. What if we could _just_ target XSS?

[Read the complete Explainer][explainer]. Also the [spec](https://mikewest.github.io/csp-next/scripting-policy.html).

## Feedback (Choose One)

Please provide all feedback below.

[explainer]: https://github.com/mikewest/csp-next/

**Comment by yoavweiss** [comment]
https://github.com/WICG/csp-next is now live
Happy incubation!

**Comment by mikewest** [comment]
Thanks! I'll close this out: https://wicg.github.io/csp-next/scripting-policy.html is up, and the old URL redirects correctly.
