### ISSUE TITLE
Support currentColor in SVG displayed in HTML5 img tag

### ISSUE THREAD

**Issue by drsounds** [WICG/proposals#50]
## Introduction

Modern web sites often embed logotypes and other glyphs as vector graphics as icon fonts or inline SVG tags or img linking to SVG files.
One problem is that modern web sites want to support both light and dark modes, which creates a problem where black areas of SVG images become obscure in dark mode. Developers currently overcome that by applying filter: invert CSS property on dark theme conditions, but this approach causes a number of drawback such cpu usage of rasterization and wrong colors.

## Use Cases (Recommended)

1 color SVG Website logotypes 

## Goals (Optional)

Add an attribute glyph which will make the black color #000 white or equalent to currentColor value. So an img ligo with this attribute would display black color in dark mode as white or what set to currentcolor

## Proposed Solution

Add an attribute on img tag color=glyph which will substitute the color #000 or black with 'currentcolor' value as if the img data were embedded in an SVG tag where fill or border color have been set to 'currentcolor'

## Examples (Recommended)

````html
...
<img src="/images/logo.svg" colorscheme="glyph">
...
````

## Alternative solution

An alternative solution would be that  browser supports the [SVG spec extended color values](https://www.w3.org/TR/SVG2/painting.html#ColorProperty) like 'currentColor' as the SVG format is used on more platforms and could allow such color scheme aware image resources to operate well with iOS and Android platform's dynamic color features such iOS .tint and Android's vector drawables.

## Privacy & Security concerns

This functionality could make it possible for scripts to track if an user has toggled dark mode.

**Comment by tomayac** [comment]
I think this should work by specifying `fill="CanvasText"`. In practice, it works for embedded SVGs, but not for SVGs referenced in `img`. Here's a quick [demo](https://flat-cooperative-orchestra.glitch.me/). I have filed this as https://crbug.com/1301269.

**Comment by martitv** [comment]
Still doesn't work. Trying to reference svg in the src of NextJS Image component. `fill="currentColor` does nothing

**Comment by yoavweiss** [comment]
Looking at the relevant [chromium issue](https://issues.chromium.org/issues/40824710#comment19), it seems like there's a way to make this work by using `color-scheme: dark light`.

**Comment by quantizor** [comment]
I don't think the linked solution addresses the actual need. For example (tailwind classes):

```html
<button class="hover:text-blue-500">
  <img class="text-current" src="./image.svg" />
</button>

<!-- image.svg -->
<svg width="17" height="16" viewBox="0 0 17 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<style>
:root {
  color-scheme: dark light;
}
</style>
<path d="M16.75 5.71429H15.6071V3.42857H14.4643V2.28571H13.3214V1.14286H11.0357V2.28571H9.89286H8.75V3.42857H7.60714V2.28571H8.75V1.14286H11.0357V0H6.46429V1.14286H4.75H4.17857V2.28571H3.03571V3.42857H1.89286V5.71429H0.75V10.2857H1.89286V12.5714H3.03571V13.7143H4.17857V14.8571H6.46429V16H11.0357V14.8571H13.3214V13.7143H14.4643V12.5714H15.6071V10.2857H16.75V5.71429ZM7.60714 14.8571H6.46429V13.7143H4.17857V12.5714H3.03571V10.2857H1.89286V5.71429H3.03571V4.57143H4.17857V6.85714H5.32143V9.14286H6.46429V12.5714H7.60714V14.8571ZM14.4643 12.5714H13.3214V13.7143H11.0357V14.8571H8.75V13.7143H9.89286V12.5714H11.0357V11.4286H12.1786V10.2857H9.89286V9.14286H7.60714V8H6.46429V5.71429H8.75V6.85714H9.89286V3.42857H11.0357V2.28571H13.3214V3.42857H14.4643V4.57143H13.3214V6.85714H14.4643V9.14286H15.6071V10.2857H14.4643V12.5714Z" fill="CanvasText"/>
</svg>

```

The image will not become blue on hover, it renders and remains white in dark mode, black in light mode.

The goal is for the SVG image to recolor automatically. This works great when the SVG is inlined, but that causes page bloat since the same asset may need to be inlined many times for all the usage throughout a website.
