### ISSUE TITLE
Isolated Web Apps

### ISSUE THREAD

**Issue by reillyeon** [WICG/proposals#56]
## Introduction

Some security sensitive applications include compromise of their application server in the threat model. For example, end-to-end encryption is designed to protect the user against the developer's infrastructure being compromised or coerced into revealing the contents of messages in transit. Transport Layer Security (TLS) and Subresource Integrity (SRI) do not provide protection against this scenario because they only prevent resources from being tampered with in transit or when hosted on third-party servers. The web's usual transport model simply doesn't allow the developer to prove that the code they delivered to a particular client hasn't been tampered with.

We propose standardizing a way of building applications using web technologies that will be able to make these kinds of integrity and authenticity assertions. They are tentatively called Isolated Web Apps (IWAs). Rather than fetching resources on-demand over HTTPS, they are packaged into [Web Bundles](https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html), signed by their developer, and verified by a trusted third party. This makes distributing updates (legitimate or otherwise) significantly more difficult and isn't a trade-off we expect most sites to accept.

[Read the complete Explainer][explainer]. 

## Feedback

I welcome feedback in this thread, but encourage you to file bugs against [the Explainer][explainer].

[explainer]: https://github.com/reillyeon/isolated-web-apps/blob/main/README.md "Explainer Title"

**Comment by likuba** [comment]
This proposal addresses some needs we have seen for PWAs/web apps as well. We would like to learn more and continue discussions around how this might be implemented to address a range of partner needs across different devices and operating systems.

**Comment by reillyeon** [comment]
@yoavweiss, can you help me migrate https://github.com/reillyeon/isolated-web-apps into the WICG organization?

**Comment by yoavweiss** [comment]
Repo now lives in [WICG/isolated-web-apps](https://github.com/WICG/isolated-web-apps)
Happy incubating!!
