### ISSUE TITLE
Shared Storage

### ISSUE THREAD

**Issue by jkarlin** [WICG/proposals#57]
## Introduction

In order to prevent cross-site user tracking, browsers are [partitioning](https://blog.chromium.org/2020/01/building-more-private-web-path-towards.html) all forms of storage (cookies, localStorage, caches, etc). But, there are many legitimate use cases currently relying on unpartitioned storage that will vanish without the help of new web APIs. We’ve seen a number of APIs proposed to fill in these gaps (e.g., [Conversion Measurement API](https://github.com/WICG/conversion-measurement-api), [Private Click Measurement](https://github.com/privacycg/private-click-measurement), [Storage Access](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API), [Trust Tokens](https://github.com/WICG/trust-token-api), [TURTLEDOVE](https://github.com/WICG/turtledove), [FLoC](https://github.com/WICG/floc)) and some remain (including cross-origin A/B experiments and user measurement). We propose a general-purpose, low-level API that can serve a number of these use cases.

The idea is to provide a storage API (named Shared Storage) that is intended to be unpartitioned. Origins can write to it from their own contexts on any page. To prevent cross-site tracking of users,  data in Shared Storage may only be read in a restricted environment that has carefully constructed output gates. Over time, we hope to design and add additional gates.

Read the complete [explainer](https://github.com/pythagoraskitty/shared-storage). 

## Feedback (Choose One)
I welcome feedback in this thread, but encourage you to file bugs against [the explainer](https://github.com/pythagoraskitty/shared-storage).

**Comment by SpaceGnome** [comment]
Definitely interested in Shared Storage API, including experimenting with it for addressing some anti-abuse use cases affected by the loss of 3P cookies.

**Comment by supanate7** [comment]
I am also interested in the anti-abuse potential of the Shared Storage API .

**Comment by piwanczak** [comment]
We're also interested in this proposal - frequency capping/measurement use case

**Comment by yoavweiss** [comment]
@jonathanKingston @supanate7 @piwanczak - Can you clarify if your support is personal or in the name of an organization? (and if it's the latter, which organization)

**Comment by yoavweiss** [comment]
Thanks @piwanczak for clarifying. That seems like enough support to move the repo over to the WICG.

**Comment by yoavweiss** [comment]
The repo now lives under https://github.com/WICG/shared-storage
Happy incubation!!

**Comment by jonathanKingston** [comment]
My views were personal, I think my organisation hasn't formed a concrete opinions yet.
