### ISSUE TITLE
Page Unload Beacons

### ISSUE THREAD

**Issue by clelland** [WICG/proposals#58]
## Introduction

[Beacons](https://github.com/w3c/beacon/) on the web are a common tool for web sites to send small amounts of data to an origin server, often used for reporting telemetry and analytics. For several reasons, though, that API (as well as other methods such as XHR, image beacons, or direct use of Fetch) is often unreliable, and difficult to use to accurately report full-page-lifecycle metrics. (See @nicjansma's excellent survey of existing techniques and their reliability in practice [here](https://nicj.net/beaconing-in-practice/))

This proposal is for an API which attempts to improve some on some of those concerns, with reliability as a primary motivation, and designed to integrate with the browser's back-forward cache. The basic mechanism involves the web site creating a "Pending beacon", which can be populated with data like existing beacons. This beacon, by default, is not sent until the page is about to be unloaded from the browser's memory, but can optionally be sent a short time after entering the bfcache, or even immediately if desired.

[Read the complete Explainer][explainer]. 

[Read the draft specification][spec]. 

## Feedback

I welcome feedback in this thread, but encourage you to file bugs against [the draft specification](https://github.com/clelland/page-unload-beacon/issues).

[explainer]: https://github.com/darrenw/docs/blob/main/explainers/beacon_api.md "Page Unload Beacon Explainer"
[spec]: https://clelland.github.io/page-unload-beacon/spec.html "Page Unload Beacon API"

**Comment by yoavweiss** [comment]
This was [discussed](https://w3c.github.io/web-performance/meetings/2022/2022-03-31/index.html#h.bvu450wrypu7) at the WebPerfWG and met with at least partial excitement.

/cc @DanShappir @ksylor @Krinkle

**Comment by tomayac** [comment]
Truly curious: if browsers like Brave consider (note, _consider_, as far as I can tell they don’t necessarily do it) blocking `<a ping>` and `navigator.sendBeacon()` (e.g., https://github.com/brave/brave-browser/issues/573), what makes you think they wouldn’t consider also blocking `PendingBeacon`?

**Comment by yoavweiss** [comment]
That's a tangent, but I believe that reporting and monitoring is a [critical part](https://github.com/w3ctag/design-principles/issues/368) of modern developement. Browsers that don't believe this to be the case would be able to block this beaconing mechanism, similarly to other ones that you mentioned. (but probably not other beaconing methods, based on image requests or fetch)

**Comment by tomayac** [comment]
Makes sense. I guess most of us agree that reporting and monitoring is crucial, and this proposal is definitely worthwhile exploring and an improvement over the _status quo_. And as even someone on the Brave issue acknowledges, these methods aren’t _exclusively_ used for tracking purposes.
