### ISSUE TITLE
Exposing Soft Navigations

### ISSUE THREAD

**Issue by yoavweiss** [WICG/proposals#71]
## Introduction

“Soft navigations” are JS-driven same-document navigations that are using the history API or the new Navigation API, triggered by a user gesture and modifies the DOM, modifying the previous content, as well as the URL displayed to the user.

https://github.com/w3c/performance-timeline/issues/168 outlines the desire to be able to better report performance metrics on soft navigation. Heuristics for detecting soft navigations can ensure that developers that follow a well-lit path can ensure their SPA’s performance metric scores properly represent soft navigations.

[Read the complete Explainer](https://github.com/yoavweiss/soft-navigations/blob/main/README.md). 

## Feedback

Feedback is most welcome!! Please file it as [issues on the explainer's repo](https://github.com/yoavweiss/soft-navigations/issues)

**Comment by cramforce** [comment]
Speaking on behalf of Vercel and Next.js, we are incredibly excited about this work as it extends the applicability of performance metrics to single page applications (such as those made with Next.js, Nuxt, Remix, or SvelteKit).

We're planning to include the metrics in our commercial RUM product as soon as they are available (stable or origin trial).

**Comment by yoavweiss** [comment]
Thanks for the support! :) The repo now lives at https://github.com/WICG/soft-navigations

**Comment by querymetrics** [comment]
The Akamai mPulse team are also looking forward to implement this in Boomerang's SPA monitoring! It will provide great insight into the user interaction and delays before the History event occurs.
