### ISSUE TITLE
An element attribute for increasing screen brightness

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/proposals#72]
## Introduction

Following [TPAC Devices and Sensors WG discussion](https://www.w3.org/2022/09/15-dap-minutes.html#t20), we'd like to explore a declarative approach for allowing web developers to ask the browser to increase the screen brightness.

[Read the complete Explainer][explainer]. 

## Feedback (Choose One)

I welcome feedback in this thread, but encourage you to file bugs against [the Explainer][explainer].

[explainer]: https://github.com/w3c/screen-wake-lock/issues/348 "An element attribute proposal for increasing screen brightness #348"

**Comment by anssiko** [comment]
Given the declarative element proposal seems to be gaining traction, it is appropriate to migrate this proposal to WICG. If successful, I expert this to find its home in the HTML LS at the end.

(Extensions to or interaction with the Screen Wake Lock API are to be discussed in/with the DAS WG.)

Please work with @yoavweiss on the transfer of relevant assets seeking review from @reillyeon and me.

**Comment by ljharb** [comment]
Can browsers even alter screen brightness on all common OS's?

**Comment by marcoscaceres** [comment]
Just voicing support for us to incubate this. Be great to continue to explore the various options.

**Comment by yoavweiss** [comment]
The repo is now at https://github.com/WICG/screen-brightness

Happy incubating!!

**Comment by anssiko** [comment]
@xfq please transfer https://github.com/w3c/screen-wake-lock/labels/control-screen-brightness%20%F0%9F%94%86 issues into this repo. @reillyeon for a co-chair sign-off.

**Comment by xfq** [comment]
@anssiko I'm not an owner of the WICG organization, and according to [GitHub Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository), it seems that issues can only be transferred between repositories owned by the same organization account. So if we decide to transfer the issues, perhaps we can only transfer the issues manually?

**Comment by beaufortfrancois** [comment]
Argh. You're right @xfq ;(

![image](https://user-images.githubusercontent.com/634478/196142491-88b62598-7015-41a8-8ec3-2785e3179d12.png)

**Comment by beaufortfrancois** [comment]
See https://github.com/w3c/screen-wake-lock/issues/348#issuecomment-1280570597
