### ISSUE TITLE
Capture all screens

### ISSUE THREAD

**Issue by shangl** [WICG/proposals#83]
### Introduction

Some companies run a managed device fleet. Some of them need a way to obtain video tracks of all screens, for such use cases as:
* Recording sessions for compliance or training reasons.
* Allowing a colleague to connect remotely and provide assistance.

The state of the art is that they need to call getDisplayMedia() multiple times, with a new transient activation each time, and instruct the user to select the "next" screen each time. This is cumbersome and error-prone. For such companies, an API that allows capturing all screens with one transient activation - or none - would be preferable. Such an API would usually be very risky and open to abuse. But in the context of managed-devices, the device can be configured to only allow the API to be invoked from a small set of allowlisted origins.

### Proposed Solution

Add a new method getAllScreenMedia that returns a promise to a sequence of media streams.

```webidl
partial interface MediaDevices {
  Promise<sequence<MediaStream>> getAllScreenMedia();
}
```

**Comment by anatmalin** [comment]
This proposal fits right into our use case.
We are a few billion dollars company with hundreds of customers (B2B) needing screen recording.
To allow quick turn around we need this exact new ability.
I hope this will become available in early 2023, to match our business needs.
Without it, our solution is limited, and we will miss our go-live target of 2023.

**Comment by arnaudbud** [comment]
Dialpad would benefit if it were able to do what Simon suggests, with no user action and no notification bar.
I support his proposal.

**Comment by yoavweiss** [comment]
The repo is now live in https://github.com/WICG/capture-all-screens

Happy incubation! :)
