### ISSUE TITLE
Set html with license

### ISSUE THREAD

**Issue by bahijab615** [WICG/proposals#85]
## Introduction
A crazy, random idea I had today would be to have an html tag for license. Usually when we access a website there is no possibility of knowing whether certain content is licensed or not - or html is licensed or not. [Read the complete Explainer][explainer]. 

## Use Cases
The proposal I have today is to solve the problem of determination and right of content by the html license tag - below is a list of license tags. For example:

**option 1: set body or head with license**
```html
<!DOCTYPE html>
<html>
<head license-type="GPL-3.0">
<link rel="license" href="GPL-3.0.txt"> 
<!--- 
 or href="MIT.txt" 
 or href="Copyright.txt" 
...  
--->
</head>
<body license="GPL-3.0">
<p>Content licensed with GPL-3.0 license </p>
</body>
</html>
```

**option 2: set meta html with license**
```html
<!DOCTYPE html>
<html>
<head>
<meta license="GPL-3.0"/>
<license type="GPL-3.0"/>
<license type="GPL" version="3.0"/> 
<!---  
or
<license type="MIT"/>
<license type="Copyright"/>
<license type="MIT" version="2.1"/>
<license type="Copyright" version="1"/> 
---->
</head>
<body>
<p>Content licensed with GPL-3.0 license </p>
</body>
</html>
```

**option 3: set html elements with license**
```html
<!DOCTYPE html>
<html>
<head>
<input type="file" license-type="GPL-3.0"/>
<input type="file" license-type="GPL" version="2.1"  />
<audio type="file" license-type="GPL-3.0"/>
<audio type="file" license-type="GPL" version="2.1"  />
<video type="file" license-type="GPL-3.0"></video>
<video type="file" license-type="GPL" version="2.1"></video>
<div type="file" license-type="GPL-3.0"></div>
<div type="file" license-type="GPL" version="2.1"></div>
<!---  
or
<input type="file" license-type="MIT"/>
<input type="file" license-type="Copyright"/>
<input type="file"="Copyright" version="2.1" />
<input type="file"="MIT" version="2.1" />
---->
</head>
<body>
<p>Content licensed with GPL-3.0 license </p>
</body>
</html>
```

**option 4: set html with license from cdn**
```html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Cdn and license</title>
    <link rel="license" href="GPL-3.0.txt"> 
    <link rel="license" href="https://democdn1.com/GPL/3/license.txt"> 
    <link rel="license" href="https://democdn2.com/GPL/3/license"> 
    <license type="GPL-3.0"/>
    <license type="GPL" version="3.0"/> 
    <!-- Imports license with democdn2 external license -->
    <link rel="import" href="https://democdn2.com/GPL/3/license">
</head>
<body>
    <!-- Runs custom element from democdn1, democdn2 --->
    <license type="GPL" version="3.0"/> 
    <license type="GPL-3.0"/>
    <img src="/logo.txt" license="https://democdn2.com/GPL/3/license"/>
</body>
</html>
```

**option 5: Document type Definition(DTD) and license**
> I had a perhaps strange or unique vision is: a document type definition(dtd) is a set of markup declarations that define a document type for an SGML, GML, IBM_Generalized_Markup_Language, SGML, XML, HTML Because a dtd defines the valid building blocks of an XML document. It defines the document structure with a list of validated elements and attributes. A DTD can be declared inline inside an XML document, or as an external. DTD is similar to package.json
> We can see this here:

```xml
<!-- Imports dtd with license with democdn2 external, license -->
<link rel="license" href="https://democdn1.com/DTD/GPL/3/license.dtd"> 
```

and here:
```xml
<!--- file license.dtd --->
  <?xml version="1.0" standalone="yes"?>
  <!DOCTYPE HELLO [
     <!ELEMENT HELLO (#PCDATA)>
     <!ATTLIST HELLO NAME LICENSE CDATA #REQUIRED>
     ]>
<HELLO LICENSE="GPL"> Hello text with licensed GPL </HELLO>
```

or here too:
```xml
<!--- another file license.dtd --->
 <?xml version="1.0" ?>
 <!DOCTYPE hello SYSTEM "contributors.dtd">
 <hello> hello licensed with contributors.dtd </hello>
```

or here too:
```xml
<!--- another file license.dtd --->
 <?xml version="1.0" ?>
 <!DOCTYPE hello SYSTEM "metagroup.dtd">
 <hello> hello licensed with metagroup.dtd </hello>
```

**option 6: Determination and right of content by the html license tag**
Each cdn network can specify certain html elements with some license or even each web compoenent within a cdn network must specify certain html elements with some license too, so I realized the use case of dtd and web component as necessary for license. For example:

```html
<!-- use case 1: Imports dtd with license with democdn2 external -->
<link rel="license" href="https://democdn1.com/DTD/GPL/3/license.dtd"> 

<!-- use case 2: Imports web component with license with democdn2 external -->
<link rel="import" href="https://democdn2.com/GPL/3/license"> 
```

## Goals
The proposal(Set html with license) is for Declarative Custom Element and Declarative Web Application:  
> *"This is definitely not random. In Web 3.0 the different vendors content is mixed into web application with own license requirements. This content is not only comes from 3rd party vendors but also served from different hosts/CDN/repositories. For Declarative Custom Element and Declarative Web Application served from outside, the license data definitely have a sense and would be a part of components acceptance protocol for portals or CMS. Going further, I would imagine the styling (outline, background, etc. ) based on this tag in DCE on edit mode in visual designers. To make it more coding-friendly, it worth to be added to own namespace exposed as to HTML as to XML with matching DTD. XSLT 4 proposed ability to mix namespaces as long as tags are not overlapping, same can be assumed in HTML."*

## Non-goals
> A curious question: Do you think this proposal can help things like DRM? 
> "The license support itself is definitely not sufficient to cover DRM needs. The abstract structured metadata like metagroup would. There are several standards of DRM. [[MS-DRM]: XML Schema for Version 7 License Response ](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-drm/fbb909e3-96bf-4fc0-843e-b56736711d6c), [Use Case 2 - XSD for DRM - W3C eGovernment Wiki ](https://www.w3.org/egov/wiki/Use_Case_2_-_XSD_for_DRM)- just to name a few.
> Having XML data island as part of metadata associated either with a HTML document (page) or any of its components would be helpful. Those components with own metadata could be any video, OBJECT, Declarative Custom Element, etc."

## Proposed Solution
The proposal(Set html with license)  is about declarative syntax, no need to circle back to JSON as a format. License information includes things like:
> "What kind of data the license need?
> type - with package.json schema 
> version 
> href - URI to text
> icon as in GitHub
> description - for accessibility via screen reader, etc.
> media to be selected by screen reader, “about application” inspector, etc."

You can use license for symmetrical entities:
> *"If the license on proposal, symmetrical entities have to be considered as well.
> [funding](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#funding)
> [aithor/contributors](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#people-fields-author-contributors)
> [repository](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository)
> [homepage](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#homepage)"*
> "As most of those could have multiple and complex entries, embedding would be needed.
> The Declarative approach for those kind of data needs abstract container with section type. The [meta](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta) tag is self closing and does not allow to include relative and long content. While it is possible to inject several license(or another) related info using prefix, repeated keys would be clunky cloning: "

```html
<meta contributors-name="aaa" contributors-email="a@b.c" />
<meta contributors-name="bbb" contributors-email="b@b.c" />"
```

*or*

> "Which given us a need for metagroup as structured content:
```html
<metagroup contributors>
<meta name="aaa" email="a@b.c"/>
<meta name="bbb" email="b@b.c"/>
</metagroup>"
```

> "The metagroup is not an ideal word, in meta definition the [metadata](https://developer.mozilla.org/en US/docs/Glossary/Metadata) refers to the abstraction layer where meta is just a holder for key-value pairs."

## Alternate Approaches
```html
<metagroup id="resource1" contributors>
  <meta name="aaa" type="" version="" href="" icon="" description="" content="Example Resource" media="" email="a@b.c"/>
  <meta name="bbb" content="1.0.0.0" email="b@b.c" />
  <meta name="language" content="en-US" />
  ...
</metagroup>
```

## Feedback
I welcome feedback in this thread, but encourage you to file bugs against [the Explainer][explainer].
> "I am looking into license and other fields from consumer point of view. Same html document could have 0+ licenses itself and web components / WC libraries own ones.
> As an application code programmer I need those to be exposed coherently in HTML DOM. XML annotations, comments and other non-dom methods do not fit into usual DOM processing routine, leaving tag-based syntax as most convenient for purpose.
> The external and embedded definitions are definitely needed. Each would serve own purpose: external is reusable and cache-able, embedded easier to process. Ideally embedded and external formats would use same syntax so “if not embedded, load external reference and process in same fashion” would be applicable. Which takes JSON like package.json or webcomponent.json out of equation as the consumption of inline and external would differ.
> Just a reminder, the proposal is about declarative syntax, no need to circle back to JSON as a format.
> XML-like format would make internal and external preference a matter of same single expression in XPath or JS."

## Contributors
@sashafirsov and wicg community

## Privacy & Security Considerations
N/A ?

[explainer]: https://discourse.wicg.io/t/proposal-set-html-with-license/6074/1 "Set html with license"

**Comment by marcoscaceres** [comment]
This already exists in HTML 😊 https://html.spec.whatwg.org/dev/links.html#link-type-license

**Comment by bahijab615** [comment]
Hi marcoscaceres.

> license as a link relationship [already exists in HTML](https://html.spec.whatwg.org/dev/links.html#link-type-license). The proposal is unclear how what's in HTML doesn't meet the use cases.

The idea is an "metagroup-html" by license (it's like the iframe idea, only instead of an iframe it would be for a license address or a set of license addresses). Example:

```html
<!DOCTYPE html>
<html>
<head>
<title>HTML with License</title>
<!---- demo 1 --->
<link rel="license" href="GPL-3.0.txt"> 
<!---- demo 2 --->
<link rel="license" href="https://democdn2.com/GPL/3/license"> 
<!---- demo 3 --->
<link rel="import" href="https://democdn2.com/GPL/3/license"> 
<!---- demo 4 --->
<link rel="import" href="https://democdn2.com/GPL/3/license.txt"> 
<!---- demo 5 --->
<link rel="license" href="https://democdn2.com/GPL/3/license.txt"> 
<!----
return `<metagroup contributors>
<meta name="aaa" email="a@b.c"/>
<meta name="bbb" email="b@b.c"/>
</metagroup>`
---->

</head>
<body>
</body>
</html>
```

**Comment by marcoscaceres** [comment]
Sorry, I’m still not following. Can you give a more concrete example? For instance, the HTML spec has an example linking to the license of an image. 

What do the licenses here apply to (i.e., what media or content exactly?)

**Comment by bahijab615** [comment]
Hi marcoscaceres.

> What do the licenses here apply to (i.e., what media or content exactly?)

What I'm describing is the use of an html element for web components or web pages. Web components have a feature called import maps. I believe we can license parts of web components as an import map.

Another use case is you add or reference the license by href. Something that the html already has as you said.
