### ISSUE TITLE
URLPattern

### ISSUE THREAD

**Issue by wanderview** [WICG/proposals#9]
## Introduction

Service workers scopes currently use a very simplistic URL matching mechanism.  We have heard from a number of sites that scopes could benefit from a more expressive pattern syntax.  In addition, web developers often need to match URLs in order to implement routing systems.

This proposal introduces a URL matching primitive that can be used both directly in javascript and in web platform APIs like service workers.

[Read the complete Explainer][explainer]. 

This proposal has been [reviewed by the TAG](https://github.com/w3ctag/design-reviews/issues/417).

There is also a detailed [design doc](https://docs.google.com/document/d/17L6b3zlTHtyxQvOAvbK55gQOi5rrJLERwjt_sKXpzqc/edit?usp=sharing) that goes into greater API and chromium implementation details.

This proposal was discussed at [TPAC 2019](https://docs.google.com/document/d/1q090ovJ4gd8wSfVtvuoZLMZ51YkiFDsEZ0Jiqi41Iys/edit#heading=h.d6e4ecicreet) and a [virtual call around TPAC 2020](https://github.com/w3c/ServiceWorker/issues/1535).

The group decided at the latest meeting URLPattern should be spec'd under WICG to start.  I'd like to move the explainer repo to WICG and rename it to urlpattern.  Eventually the service worker bits will move out to the service worker WG repo.

## Feedback (Choose One)

I welcome feedback in this thread, but encourage you to file bugs against [the Explainer][explainer].

[explainer]: https://github.com/wanderview/service-worker-scope-pattern-matching/blob/master/explainer.md "Service Worker Scope Pattern Matching Explainer"

**Comment by asakusuma** [comment]
LinkedIn is very interested in being able to handle routing across different JS environments using the same built in primitives.

**Comment by yoavweiss** [comment]
Sounds like we have enough support to move over the repo!

**Comment by wanderview** [comment]
The repo has been moved to:

https://github.com/wicg/urlpattern

Thanks @yoavweiss!

Not sure if this issue stays open or should be closed.

**Comment by yoavweiss** [comment]
Added a label indicating the repo was adopted. I think we can leave it open, use labels to keep track of progress until it's migrated to a WG.
