### ISSUE TITLE
Back/foraward cache NotRestoredReasons API

### ISSUE THREAD

**Issue by rubberyuzu** [WICG/proposals#93]
## Introduction

Currently developers can tell whether BFCache is being used or not but they cannot tell what reasons are blocking it from being used and what actions to take to improve their hit-rate. DevTools provide the testing feature to tell developers what reasons are blocking, but that is only for lab testing and not for gathering the data from the wild.

One way to solve this issue would be to provide an API to report the reasons why the page was not restored from bfcache if not.
One idea is to extend PerformanceNavigation API to include this information as below:
```
window.addEventListener("pageshow", (event) => {
  if (!event.persisted) {
    const navEntries = performance.getEntriesByType("navigation");
    for (var i=0; i < navEntries.length; i++) {
	console.log("= Navigation entry[" + i + "]");
	var p = navEntries[i];
	// p.notRestoredReasons == [{url:"a.com", id: "x", blocked: true, reasons:["Broadcast channel"], children:[]}]
    }
  }
});
```
It will have notRestoredReasons field that will contain the reasons in the frame tree structure.
Note that this would risk exposing cross-site information, so we should avoid reporting reasons from the cross-origin subframes.

[Read the complete Explainer](https://github.com/rubberyuzu/bfcache-not-retored-reason/blob/main/NotRestoredReason.md). 

## Feedback

I welcome feedback in this thread, but encourage you to file bugs against [the Explainer](https://github.com/rubberyuzu/bfcache-not-retored-reason/blob/main/NotRestoredReason.md).

**Comment by rubberyuzu** [comment]
Position requests for [Mozilla](https://github.com/mozilla/standards-positions/issues/766) and [WebKit](https://github.com/WebKit/standards-positions/issues/154).
This is the [discourse discussion](https://discourse.wicg.io/t/proposal-back-forward-cache-notrestoredreason-api/5773).

**Comment by yoavweiss** [comment]
Mozilla [seems fine](https://github.com/mozilla/standards-positions/issues/766#issuecomment-1506850077) with this repo moving to the WICG org.

**Comment by nicjansma** [comment]
We would like to have `notRestoredReasons` for our RUM measurements in Akamai mPulse. 

We are starting to track BFCache-based navigations, and with that our RUM customers will become more interested in why specific navs were not BFCache-eligable.  Gathering this information will be a huge help in pointing out the culprits in aggregate.

**Comment by yoavweiss** [comment]
The repo is now live at https://github.com/WICG/bfcache-not-restored-reason

Happy incubation!!
